Remove unused variable
Variable is assigned but not used; under GCC 4.6.1, this causes:

ag-manager.c: In function 'ag_manager_get_service':
ag-manager.c:1651:10: error: variable 'rows' set but not used
[-Werror=unused-but-set-variable]